### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by MichaelsPlayground** [KhubaibKhan4/WhatsApp-Clone#1]
This seems to be a very nice and handy app, but I'm missing two features offered in your "readme.md" document:

**Push notifications**: Users receive push notifications when they receive a new message, even if the app is closed.

**End-to-end encryption**: Messages are encrypted end-to-end to ensure privacy and security.

Did you plan to add the features at a later time ?

Greetings
Michael

**Comment by KhubaibKhan4** [comment]
Hey Michaels,

Thank you for your comment on this issue. Basically, I worked on this application 2 years ago but now working on the Kotlin Multiplatform Project (Android+iOS+Desktop+Web), So don't have enough time to work on it.

**Comment by MichaelsPlayground** [comment]
Thanks for your answer. It might be a good idea to change the project description and delete both features, thanks.
Btw: your code is very efficient so I hoped to see how the new PushNotification (HTTP V1) API is working.
Greetings
Michael

**Comment by KhubaibKhan4** [comment]
> Thanks for your answer. It might be a good idea to change the project description and delete both features, thanks. Btw: your code is very efficient so I hoped to see how the new PushNotification (HTTP V1) API is working. Greetings Michael

I hope to add them soon. If you need me for any freelance work, I'm available for you.  I can create project using Kotlin Multiplatform for all the OS.
